##
# Build Services dockerfile
# Includes the build option when building the container
##
version: '2.3'
services:
  panel:
    image: ccarney16/pterodactyl-panel:${PANEL_VERSION:-latest}
    build:
      args:
        VERSION: ${PANEL_VERSION}
      context: ./manifest/panel
  worker:
    image: ccarney16/pterodactyl-panel:${PANEL_VERSION:-latest}

