version: '2.3'
services:
  ##
  # Let's Encrypt Service
  #
  # This is the daemon version of the service. HTTP/HTTPS ports are enabled.
  # This Config will NOT be used if both the panel and daemon.
  ##
  certbot:
    command: renew
    image: certbot/certbot:latest
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./conf.d/letsencrypt:/etc/letsencrypt
  ##
  # cron
  # This is identical with the base panel version, this is included
  # to provide a cron task for the daemon and certbot
  ##
  cron:
    command: daemon --docker
    depends_on:
      certbot:
        condition: service_started
    image: mcuadros/ofelia:latest
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.le-renew.schedule: "0 0 0 * * *"
      ofelia.job-run.le-renew.container: pterodactyl_certbot_1
    network_mode: none
    privileged: true
    restart: always
    volumes:
    - ${DOCKER_SOCKET:-/var/run/docker.sock}:${DOCKER_SOCKET:-/var/run/docker.sock}
