version: '2.3'
services:
  ##
  # Let's Encrypt Service
  #
  # This is the panel version of the service, as such, it will rely on using
  # the webroot for its configuration. This panel varient will always override
  # the daemon when enabled.
  ##
  certbot:
    command: renew
    container_name: pterodactyl_certbot
    depends_on:
      panel:
        condition: service_healthy
    image: certbot/certbot:latest
    labels:
      ofelia.enabled: "true"
      ofelia.job-run.le-renew.schedule: "0 0 * * *"
      ofelia.job-run.le-renew.container: pterodactyl_certbot
    volumes_from:
    - panel
  ##
  # cron
  # This just adds a dependency requirement for certbot
  ##
  cron:
    depends_on:
      certbot:
        condition: service_started
  ##
  # panel
  # Adds labels to the panel container to operate on a restart schedule
  ##
  panel:
    labels:
      ofelia.enabled: "true"
      ofelia.job-exec.panel-reload.schedule: "${PANEL_RELOAD_SCHEDULE:-0 30 * * *}"
      ofelia.job-exec.panel-reload.command: "nginx -s reload"
